SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/PERSON_ID_PK.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','PERSON_ID_PK','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0037976.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0037976','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0038042.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0038042','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0038239.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0038239','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0038241.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0038241','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/RESUME_PK.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','RESUME_PK','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/REPORT_PK.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','REPORT_PK','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/CONVERSATIONS_ID_PK.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','CONVERSATIONS_ID_PK','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/PROMPTS_ID_PK.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','PROMPTS_ID_PK','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/PROMPTS_I1.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','PROMPTS_I1','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0039862.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0039862','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/IGCB_TASKS_LIST_IDX.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','IGCB_TASKS_LIST_IDX','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/LEAVE_PK.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','LEAVE_PK','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0040171.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0040171','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0040173.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0040173','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0040175.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0040175','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/indexes/SYS_C0040181.sql"
SELECT DBMS_METADATA.GET_DDL('INDEX','SYS_C0040181','IRM_POC') FROM dual;
SPOOL OFF;

