
  CREATE TABLE "IRM_POC"."IGCB_TASKS"
   (	"ID" NUMBER,
	"LIST" VARCHAR2(60) COLLATE "USING_NLS_COMP",
	"SEQ" NUMBER,
	"TASK" VARCHAR2(120) COLLATE "USING_NLS_COMP",
	"NAME" VARCHAR2(120) COLLATE "USING_NLS_COMP",
	"DESCRIPTION" VARCHAR2(1000) COLLATE "USING_NLS_COMP",
	"DONE" VARCHAR2(1) COLLATE "USING_NLS_COMP" NOT NULL ENABLE,
	 CONSTRAINT "IGCB_DONE_CK" CHECK (DONE in ('Y', 'N')) ENABLE,
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"

