SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/LEAVE.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','LEAVE','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/SAMPLE_CARD_GRID.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','SAMPLE_CARD_GRID','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/ORG_HIERARCHY.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','ORG_HIERARCHY','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/PERSON.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','PERSON','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/DEPT.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','DEPT','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/EMP.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','EMP','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/RESUME.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','RESUME','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/REPORT.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','REPORT','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/PAM.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','PAM','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/NEW_RULESET.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','NEW_RULESET','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/OCW23_CONVERSATIONS.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','OCW23_CONVERSATIONS','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/OCW23_PROMPTS.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','OCW23_PROMPTS','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/XX_FUSION_IBY_EXT_BANK_ACCOUNTS.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','XX_FUSION_IBY_EXT_BANK_ACCOUNTS','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/RULESET_SAC.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','RULESET_SAC','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/tables/IGCB_TASKS.sql"
SELECT DBMS_METADATA.GET_DDL('TABLE','IGCB_TASKS','IRM_POC') FROM dual;
SPOOL OFF;

