SPOOL "C:/Users/Dell/Desktop/cicd/db/triggers/EMP_TRG1.sql"
SELECT DBMS_METADATA.GET_DDL('TRIGGER','EMP_TRG1','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/triggers/DEPT_TRG1.sql"
SELECT DBMS_METADATA.GET_DDL('TRIGGER','DEPT_TRG1','IRM_POC') FROM dual;
SPOOL OFF;

SPOOL "C:/Users/Dell/Desktop/cicd/db/triggers/BI_IGCB_TASKS.sql"
SELECT DBMS_METADATA.GET_DDL('TRIGGER','BI_IGCB_TASKS','IRM_POC') FROM dual;
SPOOL OFF;

